<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit officia veniam aperiam, sapiente accusamus ducimus quidem praesentium pariatur porro alias recusandae odit neque voluptatem nemo sunt soluta omnis libero deserunt ab ipsam ea facilis, dignissimos sit!</p>
<p>Itaque obcaecati ad explicabo quo impedit maiores, repudiandae exercitationem ratione minima harum officiis esse quaerat eius placeat aspernatur beatae consequatur, eum voluptatem quasi facilis provident voluptatum sapiente? Dolores beatae illum vel doloribus explicabo ut eum repellendus iste. Eum vel ut porro molestias illum adipisci iste animi ducimus officiis dolor, neque labore debitis ipsum nemo repellendus expedita accusantium.</p>
<p>Dolores culpa quos adipisci, doloribus enim odio voluptas velit corrupti quasi deserunt vero ea aliquid consequatur sint illo tempore? Odit tempora eum culpa vero maxime reiciendis fuga saepe sapiente quas omnis ducimus porro assumenda temporibus, voluptatem labore quo illo quam molestiae voluptatibus error optio officia? Maiores atque eligendi minus! Animi, esse. Pariatur, quasi? Quis fugit aperiam in.</p>
  

Post::create([
    'tittle' => 'Judul Ketiga',
    'slug' => 'judul-ketiga',
    'excerpt' => 'Lorem ipsum ketiga',
    'body' => '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit officia veniam aperiam, sapiente accusamus ducimus quidem praesentium pariatur porro alias recusandae odit neque voluptatem nemo sunt soluta omnis libero deserunt ab ipsam ea facilis, dignissimos sit!</p><p>Itaque obcaecati ad explicabo quo impedit maiores, repudiandae exercitationem ratione minima harum officiis esse quaerat eius placeat aspernatur beatae consequatur, eum voluptatem quasi facilis provident voluptatum sapiente? Dolores beatae illum vel doloribus explicabo ut eum repellendus iste. Eum vel ut porro molestias illum adipisci iste animi ducimus officiis dolor, neque labore debitis ipsum nemo repellendus expedita accusantium.</p><p>Dolores culpa quos adipisci, doloribus enim odio voluptas velit corrupti quasi deserunt vero ea aliquid consequatur sint illo tempore? Odit tempora eum culpa vero maxime reiciendis fuga saepe sapiente quas omnis ducimus porro assumenda temporibus, voluptatem labore quo illo quam molestiae voluptatibus error optio officia? Maiores atque eligendi minus! Animi, esse. Pariatur, quasi? Quis fugit aperiam in.</p>'
    ])